### ISSUE TITLE
print `nbdev_test` cell errors to stderr instead of using `logging.warning`

### ISSUE THREAD

**Issue by seeM** [fastai/nbdev#1003]
`logging.warning` isn't great because it can get filtered out if the tested code configures the root logger to `ERROR` level (as in https://github.com/fastai/nbdev/issues/937#issuecomment-1235226711 and possibly also https://github.com/fastai/nbdev/issues/993)

I'm not 100% sure whether stdout or stderr makes more sense, but I'm leaning toward stdout because:

- IMO a test failure is part of the expected behaviour of `nbdev_test` and is not an error
- nbdev v1 printed failures to stdout (see [this line](https://github.com/fastai/nbdev1/blob/be439c834c01a9cd7bc7629818310cdb6f0cb23c/nbdev/test.py#L97))
- pytest also prints test failures to stdout (although, `unittest` prints to stderr by default so maybe this isn't a good reason)

cc @hamelsmu @jph00

**Comment by jph00** [comment]
I don't have strong feelings either way. I kinda feel like a failing test represents an error that occured, and for instance in CI that would result in a failure, so maybe I very slightly lean towards stderr. pytest is a bit different because it spits out all kinds of summary into regardless of whether there's a test failure. Also, pytest continues testing a file after a failure (i.e it considers it just part of the usual process) whereas we bail out because we consider it to be something that may cause the rest of the notebook to fail.

**Comment by seeM** [comment]
Those are good reasons. I'm leaning towards stderr now too

One last decision is between `logging.error` (we currently use `logging.warning`) vs `sys.stderr.write`. I prefer `sys.stderr.write` since I don't think that user code reconfiguring the root logger should affect `nbdev_test`'s outputs - it's a standalone command-line application IMO

**Comment by jph00** [comment]
> I prefer `sys.stderr.write` since I don't think that user code reconfiguring the root logger should affect `nbdev_test`'s outputs - it's a standalone command-line application IMO

Agreed.
