### ISSUE TITLE
Docs inconsistant for nbs and source code with sub-folders

### ISSUE THREAD

**Issue by jalew188** [fastai/nbdev#1032]
When the source code contains sub-folders, for example in my repo I have:

https://github.com/MannLabs/alphapeptdeep/blob/main/nbdev_nbs/rescore/percolator.ipynb (rescore is the sub-folder in both nbs and py module).

The html path the of this ipynb will be `.../rescore/rescore.percolator.html` (see https://mannlabs.github.io/alphapeptdeep/rescore/rescore.percolator.html), which is fine.

However, in my [index.ipynb](https://github.com/MannLabs/alphapeptdeep/blob/main/nbdev_nbs/index.ipynb) (see https://mannlabs.github.io/alphapeptdeep/#dda-rescoring), I called:

```
from peptdeep.rescore.percolator import Percolator
```
The \`Percolator\` term in the markdown cell will be translated to `https://mannlabs.github.io/alphapeptdeep/rescore/percolator.html#percolator`, which is inconsistant with `.../rescore/rescore.percolator.html#percolator`.

The nbdev version is 2.3.0 from master branch.

**Comment by jph00** [comment]
The issue is `#| default_exp rescore.percolator` -- it should be `#| default_exp percolator`

**Comment by jalew188** [comment]
No, the issue was not solved.

I would like to keep the folder structure `package_name/rescore/precolator.py` in the package.

If I used `#| default_exp percolator`, the py file will be package_name/percolator.py, which is not expected.

**Comment by jalew188** [comment]
But from your reply, I kind of know I should edit `_default_exp_` functionalities to support this, thanks

**Comment by jalew188** [comment]
In `nbdev.doclinks._get_modidx()`, insert the following code after `loc = nbpath.relative_to(nbs_path).with_suffix('.html')`:
```python
def _get_html_loc_with_subfolder(loc):
    if loc.as_posix().find('/'):
        locs = loc.as_posix().rsplit('/', maxsplit=2)
        loc = Path(locs[0])/Path('.'.join(locs)).with_suffix('.html')
    return loc
loc = _get_html_loc_with_subfolder(loc)
```

This is a urgly solution but works for me.

**Comment by jalew188** [comment]
thanks

**Comment by seeM** [comment]
IIUC, the issue is that we set each notebook's `output-file` to its `default_exp` ([source](https://github.com/fastai/nbdev/blob/b41634ea6780cbe958fdbbdff785f7d9e35ed7ee/nbdev/frontmatter.py#L67-L68)) but in `_modidx` we build the same notebook's HTML `loc` using its filename ([source](https://github.com/fastai/nbdev/blob/b41634ea6780cbe958fdbbdff785f7d9e35ed7ee/nbdev/doclinks.py#L59-L61)).

So the fix is to either:

1. Build the HTML `loc` using `default_exp` (perhaps using the `mod_name` variable already handy in `_get_modidx`), or
2. Set `output-file` using the notebook filename with prefix removed (we could even reuse [this regex](https://github.com/fastai/nbdev/blob/b41634ea6780cbe958fdbbdff785f7d9e35ed7ee/nbdev/doclinks.py#L60), maybe wrapped in a function)

I prefer 2 because it keeps a 1:1 correspondence between your notebooks folder and Quarto website URLs, which would also lead to simpler modidx logic. I can't think of any downsides.
