### ISSUE TITLE
Run fastai/workflows/quarto-ghp@master failing 

### ISSUE THREAD

**Issue by thigm85** [fastai/nbdev#1087]
Failure description:
```
AttributeError: path_
Error: Process completed with exit code 1.
```
Link: https://github.com/thigm85/learntorank/actions/runs/3073553347/jobs/4965761883

**Comment by omlnaut** [comment]
This started appearing today for me. A new nbdev project does not reproduce the error.

**Comment by omlnaut** [comment]
Moving the notebooks from the nbs folder to the repo-root (and adjusting settings.ini accordingly) fixes the problem...

**Comment by jph00** [comment]
The issue is that `_quarto.yml` has now changed. Remove your `_quarto.yml` and it'll generate the correct new one for you.

I've just added some code in the latest release that should do this automatically.

This new approach is much more flexible. A file named `nbdev.yml` is auto-generated and included in your `_quarto.yml`, and this is the only bit that has the stuff that's copied over from `settings.ini`.  The rest of `_quarto.yml` you can change however you want, to fully take advantage of all the features of quarto.
