### ISSUE TITLE
took a while to find 00_core.ipynb in tutorial

### ISSUE THREAD

**Issue by daveramseymusic** [fastai/nbdev#1144]
https://nbdev.fast.ai/tutorials/tutorial.html#edit-00_core.ipynb

It was in the "nbs" folder.  You might change the language to tell a user to open the "nbs" folder.

**Comment by dleen** [comment]
Hi @daveramseymusic, thanks for reporting this issue!

I think the problem here is that creating via the github template results in a flat structure like in the tutorial but using `nbdev_new` results in the notebooks inside `nbs` folder. This behavior was changed in #1083. I'll make a PR to update the docs

cc @seeM
