### ISSUE TITLE
MP4 files does not rendered with nbdev_preview

### ISSUE THREAD

**Issue by hdocmsu** [fastai/nbdev#1151]
#1088 - This issue was fixed and the embedded GIF files are shown in both Jupiter notebooks and rendered HTML - after running `nbdev_preview`

However, when I embed MP4 files using `display.HTML(<video src='./media/test.mp4’>)`, the mp4-files were not automatically copied to _proc and _doc and they were not displayed in preview (after running nbdev_preview) and the error message is `/media/test.mp4 (404: Not Found)`. 

Note that, the mp4 files are appropriately shown on Jupyter Notebooks.

Thanks in advance for any suggestions or helps to resolve this issue!

**Comment by seeM** [comment]
You need to update your `_quarto.yml` to explicitly mark .mp4 files as "site resources" (see [quarto docs](https://quarto.org/docs/websites/website-tools.html#site-resources)), else it won't be copied over into the quarto site directory (`_proc/_docs` by default for nbdev projects). Like so:

```yaml
project:
  type: website
  resources:
    - '*.mp4'
```

BTW, quarto has its own [suggested way of including videos](https://quarto.org/docs/authoring/videos.html) which has nice controls and stuff, but doesn't render in notebooks. Otherwise you might want to add some extra bits to your HTML tag:

```python
HTML("<video src='/media/test.mp4'> controls class='img-fluid'")
```

This should solve your issue, so I'll close this and reopen if needed :)
