### ISSUE TITLE
Define notebook title and description through plain front matter

### ISSUE THREAD

**Issue by leemengtaiwan** [fastai/nbdev#132]
Note: repost here as suggested by @hamelsmu :)

**Is your feature request related to a problem? Please describe.**

I know we can specify a post's title and description this way in the jupyter notebook:

```text
# my title
> a description

- toc: false 
```

But I really want a way to specify all the metadata including `title` and `description` using following more unified format, how can I achieve this:

```text
- title: my title
- description: a description
- toc: false 
```

I have tried setting `titles_from_headings` in `_config.yml` but `my_title` just got ignored and all I got is the default `Title` for a post's title.

```text
titles_from_headings:
  enabled:     false
  strip_title: true
  collections: true
```

**Describe the solution you'd like**

Able to specify title and description in following format:

```text
- title: my title
- description: a description
- toc: false 
```

**Comment by sgugger** [comment]
I see two problems with that. First: why would you not want the title to be the tile of the notebook? The goal is to have your notebooks look like the end result, not be some weird code. Note that you can already do the description as:
```
# my title
- description: a description
- toc: false 
```

Second and most annoying, how would nbdev distinguish such a cell from a regular markdown list? It would require a new special comment. So that would then make the cell look even more like random code instead of the end result, and the end user would need to remember an extra key word.

Closing in any case since we only keep issues for standing bugs. Please use the forum for feature request. If there is enough interest and someone wants to implement it, I'll happily review a PR, but this does not seem like a useful add to me.
