### ISSUE TITLE
Undocumented assumption in "installation" and "tutorial"

### ISSUE THREAD

**Issue by hwine** [fastai/nbdev#141]
_Disclaimer: I'm a conda/jupyter n00b user - I've always run virtualenv specific jupyter servers. Which is a hassle with the changing ports. So I may be missing something "obvious" about how these work together._

The instructions say "`pip install nbdev`", however they don't say in what context it should be done. The video gives the impression conda/jupyter/nbdev can be setup so your default jupyter invocation points to a parent directory of where the `nbdev` template repository is cloned.

While any help is appreciated, the ideal layout (for me) would be:
a) a conda managed jupyter environment
b) a choice of jupyter kernels for different python versions (3.x) (i.e. for generic notebook creation)
c) separate conda environments per project

Here are the questions I have after reading & listening to the tutorial:
- Which of those environments need to have `nbdev` installed into them? 
- When does the environment need to be activated? (There's no mention in the tutorial.)
- What is your workflow to allow a single jupyter deployment to service multiple repositories?

**Comment by sgugger** [comment]
I think those questions would be better ask on the [forum](https://forums.fast.ai/c/fastai-users/nbdev/48) since there are more people looking and interacting there.

I personally only have one developing env so I don't have the answers but obviously, you will need `nbdev` installed in each env you are working with it. Jupyter takes the environment in which it was launched, so you can't develop for multiple envs in one session, you need to shut down jupyter, change env then relaunch it.

As for which env needs to be activated, you would need to be in the one you developed package foo when launching commands like `nbdev_build_docs` from the terminal inside the foo repo.

**Comment by hwine** [comment]
My reason for filing the issue is that I believe these questions need to be addressed in both:
* the installation instructions, and
* highlighted in the tutorial

Following the instructions results in a non-working tutorial. Which isn't a pleasant introduction to the project.

FYI, you can handle multiple envs in one session -- you just have to:
* create a separate conda environment for each project,
* install "[Notebook Conda Kernels](https://docs.anaconda.com/anaconda/user-guide/tasks/use-jupyter-notebook-extensions/#notebook-conda-kernels)", which makes those envs available in your jupyter session, and
* change your notebook's kernel to the appropriate one after opening a notebook.

However, it sounds like such a setup is outside the scope of `nbdev` at this time.

**Comment by sgugger** [comment]
I welcome any PR clarifying the installation instructions or the tutorial.
