### ISSUE TITLE
hide_output in README.md

### ISSUE THREAD

**Issue by lgvaz** [fastai/nbdev#156]
In `index.ipynb` I marked some cells with #hide_output, but the annotation is not correctly being parsed, the current results at `README.md` is a follows:

---
```python
#hide_output  
code here...
```
Output here

---

**Comment by sgugger** [comment]
I don't think `hide_output` flags are supported in the conversion to Markdown. Will have look when I have time.

**Comment by pete88b** [comment]
this might be really simple - because `convert_nb` already calls `hide_cells` and `collapse_cells` via `process_cell` ...
we could
- create hide-md.tpl (as a copy of hide.tpl) - change hide-md.tpl to extend from markdown.tpl
- update jekyll.tpl and md.tpl to extend from hide-md.tpl

and get all of the hide/collapse behaviour.

If this sounds OK, I can do some proper testing and create a PR

**Comment by sgugger** [comment]
Sure, you can go ahead and test if you want to tackle this one.

**Comment by pete88b** [comment]
I think I have a fix https://github.com/fastai/nbdev/pull/157

**Comment by sgugger** [comment]
Should be fixed by #157
