### ISSUE TITLE
NoExportPreprocessor runs cells that are exported

### ISSUE THREAD

**Issue by pete88b** [fastai/nbdev#163]
The docs for `NoExportPreprocessor` say "... executes cells that are not exported ..." but exported cells are run during testing.

![image](https://user-images.githubusercontent.com/11458288/83061971-c2422300-a055-11ea-8514-0db6c81b230e.png)

```
nbdev_test_nbs --fname 70_test_no_export_preprocessor.ipynb 
testing: /home/peter/github/pete88b/decision_tree/70_test_no_export_preprocessor.ipynb
...
Exception: Expected [] in `test_log` but found ['nbdev_export', 'nbdev_export_and_show', 'nbdev_export_internal']
```

Should `NoExportPreprocessor` be updated to not execute exported cells? or do we just need to update the docs?

**Comment by sgugger** [comment]
I didn't update the documentation, it does run the exported cells: at first I was just not executing them and importing the default_exp module, but the problem is that cell exported can be exported in other modules so I didn't manage to have everything.
Thus it's just easier to execute everything except the cell marked with some test flags.

Will update the doc.
