### ISSUE TITLE
the /flags link is broken

### ISSUE THREAD

**Issue by hamelsmu** [fastai/nbdev#200]
The link [https://nbdev.fast.ai/flags](https://nbdev.fast.ai/flags) is broken on this page

![image](https://user-images.githubusercontent.com/1483922/89213051-5a3e1a80-d579-11ea-80d0-1180654e34d1.png)

**Comment by hamelsmu** [comment]
I would try to fix this but I still havent' been able to resolve my dependency issues with nbdev :(

**Comment by pete88b** [comment]
This could be a little tricky ...
nbdev is converting flags (surrounded by back-ticks) to a link to the doc page for the flags module but ... in this case
- we just want "flags" to be formatted as code: because it's a parameter name

We've used flags as a parameter name in a few notebooks so I think we'll find a few more broken links like this.

I'm away for a couple of weeks but I'm happy to take a look if no-one else picks this up before I get back

**Comment by jph00** [comment]
I'll happily leave it for you @pete88b :) Let me know if you have any questions.
