### ISSUE TITLE
doc_link doesn't understand default export

### ISSUE THREAD

**Issue by pete88b** [fastai/nbdev#220]
nbdev allows module names to be different to notebook names via %nbdev_default_export but ... `doc_link` forces them to follow a specific pattern (if you want backtick links to your modules).

Please see [this demo page](https://pete88b.github.io/nbdev_demo/text_utils.html) for a more detailed explanation.

I'd really like to write a map of module to notebook names to _nbdev.py
- so doc_link doesn't have to assume that module and notebook names correspond and
- make `is_lib_module` work even when your project is not in `sys.path`

**Comment by jph00** [comment]
I think I've come up with a pretty good way to create a system-wide mapping, that will also allow namespace extension modules to work. Basically, I think we might be able to leverage setuptools entry points for this functionality.

In other news, nbconvert 6 is out, and has broken pretty much everything :( I've pinned the version number for nbdev for now to work around this problem. When I do tackle the upgrade, I'm reasonably likely to remove the magic and callback functionality, since although it's extremely cool, it's beyond my ability to understand and maintain - so you might want to create a fork in you're interested in continuing to maintain that functionality.

**Comment by pete88b** [comment]
Not great news about nbconvert 6 @jph00 )o: please feel free to at-mention me if you'd like to offload any of this work.

Makes sense to kick out magic flags and callbacks - if it turns out people miss them, I think both could be implemented without changes to nbdev (i.e. by pre-processing notebooks before nbdev processes them).

**Comment by jph00** [comment]
Thanks so much :)

**Comment by jph00** [comment]
@pete88b it'll be a while b4 I can look at this, so if you do happen to have the time and inclination to remove either or both of these, I'd be *very* grateful! (But please don't feel obliged, mind you...)

**Comment by jph00** [comment]
@pete88b I'm going to start working on removing the magic flags now, so let me know ASAP if you've already made a start! :)

**Comment by jph00** [comment]
OK magic flags removal is done now. (In master, not released)
