### ISSUE TITLE
Docs: Add tutorials in Sidebar 

### ISSUE THREAD

**Issue by Matt3164** [fastai/nbdev#26]
Hey, 

First of, thanks for nbdev 😀.

I am struggling to put all my tutorials under the same toggle in the sidebar like you do in fastai2.

I named my notebooks : 
- 0x_tutorial.how_to_read_an_image.ipynb
- 0x_tutorial.how_to_compute_histograms.ipynb

I wanted to get them under the same toggle in the sidebar but no luck so far. Even digging into the fastai2 or nbdev repo...

So How can I achieve my goal? 

Getting in a Tutorials toggle in the sidebar:
Tutorials/
  - How to read an image 
  - How to compute histograms

PS: I have digged into the fastai2 repo and got the idea from there 😉

**Comment by sgugger** [comment]
Hi there! For future reference, we take questions on the dedicated topic on the [forum](https://forums.fast.ai/t/nbdev-discussion/59145) (there is even the answer to yours ;) ) and keep github for bugs only.

As for your request you need to manually edit the file docs/sidebar.json created automatically by the command `nbdev_make_docs` (look at the one in the fastai v2 project to get a feel of how you need it). Then don't forget to set `custom_sidebar=False` in your settings.ini, otherwise the command `nbdev_build_docs` is going to erase your changed and go back to the default behavior.
