### ISSUE TITLE
https://nbdev.fast.ai/conda.html 404 error

### ISSUE THREAD

**Issue by kessido** [fastai/nbdev#283]

**Comment by massgh** [comment]
This error is happened to my documentation page [pivotpy](https://massgh.github.io/pivotpy/) as well. No file other than index.html is shown.

**Comment by erictleung** [comment]
Looks like it was removed in this commit https://github.com/fastai/nbdev/commit/4cab604cc8edc5fb927d9da830a2c2dd56d54bfe#diff-28b66cf89ad7f55e4e99abdf9716084ab0f20e9ed72a732b7cfc3d35b9e6d713

**Comment by massgh** [comment]
I found the issue by locally serving docs. Instead of keeping html file itself, it creates a folder with same name and put index file in it with same content. I can see docs if `.html` is clipped from address, but cross-referencing is still issue. It seems a recent update made this kind of folder change while `nbdev`  did not managed to change addresses yet.

**Comment by DavidykZhao** [comment]
I encountered the same issue, Under docs/sidebar.json, all of the paths are automatically appended `.html` at the end, which causes the problem.
