### ISSUE TITLE
I've lost the thread

### ISSUE THREAD

**Issue by AllenDowney** [fastai/nbdev#290]
This is feedback about the documentation -- my goal is to let you know what roadblocks I'm hitting as a new user.  I hope this is helpful.

I followed the tutorial and tested everything using a minimal repo based on the template.  So far so good.  Now I am ready to add more material to the repo and try out additional features.  So that's what I'm looking for next.

But the next item after the tutorial is this page:

https://nbdev.fast.ai/export.html

I started reading that, and immediately I have lost the thread of what we are doing.  I don't understand what this page is telling me or why.  Is this what I need to know next?  Or is this information about the implementation that I don't need to know?  I can't tell.

The next item is

https://nbdev.fast.ai/sync.html

This is better.  I understand what this page is about, but I don't need it yet.  So, on to the next:

https://nbdev.fast.ai/showdoc.html

I think I understand this page, but it's not explicit about what problem it is solving, and I think I don't need it yet.

Sorry if this is too much detail -- my point is that as a beginner exploring this tool and deciding whether to continue, I have hit a stopping point after the tutorial.

The next steps I need help with are

1. Now that I have a minimal repo working, how do I get from here to doing real work?

2. Rather than starting a new project from scratch, what I really want to do is fit an existing project into this framework, so I could really use documentation for that.

3. I am actually considering using nbdev to generate a book rather than a Python library, so I would like to find documentation for that.

This looks like a really useful project, and I understand that writing documentation is hard.  So I hope this feedback is more helpful than annoying :)

**Comment by hamelsmu** [comment]
@jph00 I'm willing to work on this together.  This seems like useful feedback.  

Thanks @AllenDowney I'm forever a fan of your books and your teaching, so happy to see you here!

**Comment by hamelsmu** [comment]
Talked to @jph00 ... I'm working on this now ... will build a small nbdev project with all the things you might want to do, and document all my steps.  

Afterwards, I'll update the nbdev docs appropriately.

**Comment by jph00** [comment]
@AllenDowney thrilled to see you here - I'm a fan too! To clarify, this is the tutorial you went thru? https://nbdev.fast.ai/tutorial . Did you watch the video there?

What "real work" would you like to do next?

@hamelsmu is planning to show you an example by converting a bit of your ThinkPython2 repo to nbdev, and showing the steps. I hope that will help. `nbdev` is reasonably mature and quite widely used, so hopefully you'll find, despite the missing doc piece between the tutorial and the "now what?", that it is effective for creating python libraries for you.

For writing a book, we have `fastdoc`, which is what we used to write our O'Reilly book, which is here: https://fastai.github.io/fastdoc/ . However, we haven't done much at all to turn it into something more generally usable, other than adding some very minimal docs. Unlike nbdev, it's not widely used at all - it's only a few days since we made it public at all! We plan to do more, but it's not an immediate priority. We are aware of other folks who are starting to use it to write books. `fastdoc` takes your notebook and spits out an asciidoc file that is suitable for sending to O'Reilly, or for converting into docbook or whatever format your preferred publisher needs. I'd be more than happy to take you thru it over a Zoom call or similar if you'd like to learn more - we'd love help from other authors with improving the documentation and adding any features that other folks need.

**Comment by AllenDowney** [comment]
Hi All, and thank you for the quick replies!

@jph00 , yes, that's the tutorial I followed, but I did not watch the video.  I'll do that.

@hamelsmu , thanks for using ThinkPython as an example, that sounds like it will be a huge help.

And I will check out `fastdoc`, because I think that's probably the next step for me.

**Comment by hamelsmu** [comment]
@AllenDowney if you need immediate help getting started or are blocked, I'm willing to help you in the meantime or to even pair with you to get you unstuck.  I'm hoping to get a minimal "quickstart" guide for you soon though!

**Comment by AllenDowney** [comment]
@hamelsmu Thank you, that is a very kind offer.  I have switched to another project for now, so it is not urgent.  When I switch back, I will check with you, and I would be happy to test anything you've written.

**Comment by willingc** [comment]
@hamelsmu @jph00 @AllenDowney :wave:

Going through the install in the README (which I believe is the same as the rendered doc). Saw some things that tripped me up while just getting started:

1. Missed the "Required" comment at the top of `settings.ini` and ran into a few parameter not found errors
2. Missed the "branch" parameter completely. I may have deleted accidentally when editing the file so had to add when the `nbdev_build_lib` errorred.
3. I may have been dense but I wasn't sure what belonged in host (github or my github username) also was a bit confused with `lib_name` and `repo_name`.
4. Is there a formatting reason that prevents breaking up the README installation into steps.

Hamel, hope this helps as you write a more in depth tutorial.

**Comment by jph00** [comment]
Thanks a lot Carol - we'll fix those up. There's no formatting reason we can't split things up in the README.

Please do let us know if anything else is less than clear.

BTW, the "branch" setting is indeed there in the template, so I guess somehow it got deleted during editing:
https://github.com/fastai/nbdev_template/blob/master/settings.ini

**Comment by hamelsmu** [comment]
@willingc thanks for trying out nbdev, I am beyond excited that people like yourself are trying it out!  I am still working on my minimal example (#298 ), which has been more work than I anticipated (writing is hard, especially when you want it to be good  and short!). 

P.S. The offer I extended to @AllenDowney applies to you as well if you need to get unblocked while getting started on something.

**Comment by hamelsmu** [comment]
@AllenDowney @willingc We have authored [a new page in the docs - A minimal example with nbdev](https://nbdev.fast.ai/example.html) that we think helps readers solidify understanding of `nbdev`.  

**As a bonus we use a bit of @AllenDowney's code, specifically `Cards.py` from ThinkPython2 for illustrative purposes.**   Concretely, we show you how you might write the code, docs, and tests associated with `Cards.py`  and highlight the benefits of `nbdev` over a traditional development environment while doing so.

Would love to hear your feedback after you have had a chance to step through these new docs.  Thanks again for providing us with feedback.  I would love to see how we can enable `nbdev` to be used in your teaching and your work. 

 I have been using it every day for the past couple of months, and it has completely changed my life!

**Comment by willingc** [comment]
I will go through in the next few days. I'll open a PR for any things that I see.

**Comment by hamelsmu** [comment]
@willingc we also just [improved the README](https://github.com/fastai/nbdev/blob/master/README.md) after thinking deeply about your experience so that people are directed to the right tutorials and examples.  

Thanks again to both of you @AllenDowney @willingc for taking the time to give us feedback, really looking forward to what you find as you take another look!

**Comment by hamelsmu** [comment]
@AllenDowney @willingc just a friendly bump / reminder that would really love your feedback once you have a chance to go through the example.  

@AllenDowney would be especially interested if you think another example from one of your Think* books might be helpful or if this one is appropriate.  Thanks and appreciate everyone's involvement!  Really excited to have ya'll try the end-to-end walkthrough 🙇 .
