### ISSUE TITLE
Numpy and Google Docstring Style Support

### ISSUE THREAD

**Issue by massgh** [fastai/nbdev#356]
The docstring in nbdev is not rendered properly, for example numpy and Google style docstrings are rendered unexpectedly such as
```
Parameters
----------
```
becomes Heading 1 which shows up in TOC as well.
When are you going to fix it? Currently I am struggling with making bullet points to render documentation properly.

**Comment by hamelsmu** [comment]
nbdev docs rendering does not specifically support Google / numpy docstrings.  I would suggest writing your docs in the nbdev way instead by moving the docs into the notebook instead of trying to document the function in a docstring.  Only the first line of the docstring is rendered in the docs, with the assumption that explanation of parameters, etc will be done in the notebook.   A good example is fastcore's [store_attr](https://fastcore.fast.ai/basics.html#store_attr). 

> When are you going to fix it?

☝🏽 P.S. this is not an appropriate tone or question to ask in any open source project.

**Comment by massgh** [comment]
@hamelsmu I am sorry about that. And I got your point that nbdev has its own way of documentation. Thanks

**Comment by ulupo** [comment]
I dare to guess that people (I was one of them) can get the impression that this style of documentation is supported by looking at the introductory documentation, e.g. the [minimal example](https://nbdev.fast.ai/example.html), see the docstrings for the `Card` class there where "Attributes" are explicitly documented in a similar style.  Later in that same page (Step 4 -- Preview The Docs), a preview is shown demonstrating that indentations, new lines, monospace and the like are not what one might have hoped. But this is not explained in the body of text.

As a way of suggesting an enhancement, may I suggest that the minimal example page be reworked to avoid using this "Attributes" section, instead explicitly pointing out in the body of text that numpy/Google-style docstrings are not rendered as one might expect?
