### ISSUE TITLE
Customize Documentation Page / Theme

### ISSUE THREAD

**Issue by leemengtaiwan** [fastai/nbdev#39]
Thanks for the project, very excited about this! I managed to set up my first nbdev documentation page as the tutorial under my domain:
- https://leemeng.tw/datascience_toolkits/# 

I want to go a step further to customize the documentation page to make its style consistent with my own existing blog (which is set up by [Pelican](https://docs.getpelican.com/en/stable/)):
- https://leemeng.tw

Do you have any advice or direction where should I start or look into? For example, is there an easy way to switch from Jekyll to Pelican? If the Jekyll is the way to go, what are the recommended way to customize style?

I'm sure when `nbdev` becomes super popular, these questions will be asked frequently. Thanks in advance!

**Comment by sgugger** [comment]
Hi there!
I have no idea on how to begin since I haven't used Pelican a lot and forgot pretty much everything about it. The documentation style is defined by the css in the base template, it is certainly possible to customize those.

I think you would find more help on the [forum](https://forums.fast.ai/t/nbdev-discussion/59145) since this is where we usually have all discussions. Closing the issue as we keep them for standing bugs only and I encourage you to start a new topic on the forum! 
If you encounter problems during the conversion, ping us and we'll see what we can do to help.
