### ISSUE TITLE
How do I use nbdev without GitHub?

### ISSUE THREAD

**Issue by PhilipMay** [fastai/nbdev#446]
Hi,
I very much like nbdev but for me it seems like it is very much coupled with GitHub.

I would like to evaluate how to develop internal company software with this tool.
Also I would like to avoid a vendor lock-in with GitHub to be honest.

Can you please say how I can use nbdev without GitHub but with an internal company GitLab for example?
Which features will miss if I do not use GitHub but maybe GitLab?

Small remark: Maybe you want to add this question / the answer to your nbdev documentation?
Not all companies or data science ppl. develop FOSS.

Thanks
Philip

**Comment by hamelsmu** [comment]
Its fairly wired to GitHub at this point -> especially the repo template/creation process.   We made that choice deliberately to make the setup easier for most people.  I certainly understand the desire to use it elsewhere, and it is definitely possible with some tweaks -> But we would have to test it against other platforms to make sure whatever instructions we provide  work.  

I'll mark this issue as something we may want to revisit.  

cc: @jph00 

Can you elaborate on what you mean by this comment? 

> Not all companies or data science ppl. develop FOSS.

**Comment by PhilipMay** [comment]
@hamelsmu and @jph00  thanks. That would be great.

If you want this tool to expand IMO you should describe how companies can use it in their own network without GitHub.

**Comment by PhilipMay** [comment]
> Can you elaborate on what you mean by this comment?

I mean that there are companies that think nbdev is a great tool and want to use it for their own development.
But might think that it is not possible because they do not want to put their code on GitHub.

FOSS: https://en.wikipedia.org/wiki/Free_and_open-source_software

**Comment by hamelsmu** [comment]
I know what FOSS is.  I invite you to reflect on this statement.  I asked you to elaborate because I found it offensive, but wanted to give you the benefit of the doubt.  It seems like you may not have any awareness so I think I need to point it out.   

Let's think about this statement:

> Not all companies or data science ppl. develop FOSS.

- It has a condescending tone
- `develop FOSS` :  Excuse me?  Why do you feel you have the right to demand something?

You need to check yourself.  I'm closing this issue for now.  Try to be more respectful towards others in the future.

**Comment by carolinarsm** [comment]
@hamelsmu 
Reopening just to ask about a specific case. Apologies if this is not the right place.
We use Github Enterprise on-premise, due to sensitive data considerations, and I've been trying to find if it's possible to use nbdev there, without much success. If it's indeed possible, those tweaks you mentioned could prove very helpful.



PS: just for peace of mind, I read Philip's comment and was curious about what was offensive. As a non-native English speaker I'm almost 100% sure he's abbreviating "people" as "ppl.", so, the phrase expands to "not all companies or data science people develop FOSS" (we use this syntax all the time in my country. With global communications, misunderstandings are bound to happen!)

**Comment by hamelsmu** [comment]
>  I've been trying to find if it's possible to use nbdev there, without much success. If it's indeed possible, those tweaks you mentioned could prove very helpful.

Where are you getting stuck?
