### ISSUE TITLE
[Question] answer not found through documentation / tutorials

### ISSUE THREAD

**Issue by dsm-72** [fastai/nbdev#598]
Hello,
I am an interested in using `nbdev` as it is very similar to how I currently develop (a directory of notebooks to iteratively develop code, and then a python module where I place the completed / documented code). In your tutorials / documentation, there are two things I don't find readily addressed. 

### Question 1
How to properly include "example" notebooks. Nbdev allows use to develop in notebooks and export that code into modules which `nbdev` turns into a python package. If I wanted to include full examples of how to use this package, what is the proper way to do this? Include a notebook e.g. `##_example_1.ipynb` and then import it into `index.ipynb`? Or do I restructure my repository to be:

```
project_root
| -- examples/        # <--- where I create complete tutorials? 
| -- nbdev/             # <--- where I create the nbdev project
| -- scripts /           # <--- where I put scripts that use that interface / use the package made under nbdev?
``` 

### Question 2
How do I  include scripts as part of the project?
(python) scripts are normally just `py` files. Do I put the code in a notebook and let it get bundled with the package? If so, how?

**Comment by jph00** [comment]
@jvivian's advice sounds good to me. And for modules/scripts, just include them like you would in any normal Python lib. No need to use a notebook for that.

**Comment by jvivian** [comment]
> @jvivian's advice sounds good to me. And for modules/scripts, just include them like you would in any normal Python lib. No need to use a notebook for that.

By this you mean colocate them in the module directory built from `export`? 

What the OP may be asking, and is somewhat related, is the best practice for handling arbitrary paths to included files?

Since the notebooks and module code live in different directories and therefore have different relative paths, I've run into this problem where at the top level I have my notebooks and the module directory `src` and a `data` directory with my files. Code I write in the notebooks knows to look in `./data` for the file, but then when I export it, doesn't know to look up a directory `../data`.  

I'm guessing there's an obvious way to handle this, but I didn't seen any reference to this in the documentation (I checked the fast.ai repo to see if I could find that use case and how you solved it, but didn't see anything when I glanced).

Thank you again Jeremy,
John

**Comment by dsm-72** [comment]
@jvivian yup. Since by default notebooks are in the root of the directory even if you try and use `__file__` to create relative paths, the bundle functions differently than the notebooks.

Basically I am asking for a more fledged out example for nbedv tutorial. 

Like, ok, I have my package `package`, it is bundled and pushed to pypi and conda. It even has some scripts using my library. How do I make sure that when the user `pip install package` they can run `python -m script-from-package`.
