### ISSUE TITLE
Auto-generated showdoc headers not in ToC

### ISSUE THREAD

**Issue by jph00** [fastai/nbdev#703]
Should have been fixed in Quarto here:

https://github.com/quarto-dev/quarto-cli/commit/dbb9de99a1ad959d1d6e064654002a8247138289

Check whether `#| output: asis` fixes it.

**Comment by jph00** [comment]
Seems to be a quarto issue. Reported to @jjallaire via email.

**Comment by jjallaire** [comment]
We actually needed to change that behavior because the "automatic" application of as-is output was surprising and broke other things (e.g. it broke the cross-referencing of pandas generated tables because we lost the enclosing output div). While attempting to intuit the user's preference for `output: asis` automagically seemed like a good idea at the time, we decided that having the behavior being explicit and deterministic was better long term (and that it was further better that we make this change prior to v1.0 rather than after).
