### ISSUE TITLE
possibility of using pyproject.toml instead of settings.ini?

### ISSUE THREAD

**Issue by hugolytics** [fastai/nbdev#709]
The settings.ini file contains information conventionally stored in pyproject.toml. since the pyproject.toml structure is being increasingly adapted, for example by mainstream tools like poetry, or best practice focused ML platforms like Kedro, it makes sense for nbdev at least accommodate keeping settings DRY, by reading the required information (such as repo, version number, author, description, etc.) from the pyproject.toml file, and additional nbdev specific information under the [tool.nbdev] header.

are there any plans or discussions to implement this, or am I suggesting something completely crazy :p?

**Comment by jph00** [comment]
Definitely not crazy. settings.ini predates the pyproject.toml metadata PEP and I don't think it's really compatible with it. There's only a small number of settings in there that we use, and lots of settings we use that aren't in there (or at least in the poetry version that's pretty standard).

I would be open to considering a PR that adds a command to auto-generate a pyproject.toml file from settings.ini (and settings.ini can have any other metadata you like in it without causing problems, so if there's stuff pyproject.toml needs that settings.ini doesn't have, that wouldn't be a problem).

I'll close this issue since I don't think there's any immediate follow-up required, but if you've got ideas to add feel free to reply here or to create a new issue or PR with a more detailed proposal.

**Comment by michaelaye** [comment]
Is this becoming more urgent?
Currently getting this pip warning when installing on 3.12:

>DEPRECATION: Legacy editable install of coreg[dev]==0.14.0 from file:///Users/maye/Dropbox/src/nbcoreg (setup.py develop) is deprecated. pip 25.0 will enforce this behaviour change. A possible replacement is to add a pyproject.toml or enable --use-pep517, and use setuptools >= 64. If the resulting installation is not behaving as expected, try using --config-settings editable_mode=compat. Please consult the setuptools documentation for more information. Discussion can be found at https://github.com/pypa/pip/issues/11457
```

**Comment by jph00** [comment]
@michaelaye what exact command did you use to install that resulted in this message?

**Comment by michaelaye** [comment]
`pip install -e .`
this issue might only exist for editable installs: https://peps.python.org/pep-0517/

**Comment by michaelaye** [comment]
did you mean you added it to `nbdev_export` ? I don't see yet any related release on GH nor do I see it appearing after executing the export?

**Comment by jph00** [comment]
Here: https://github.com/fastai/nbdev-template
