### ISSUE TITLE
Tutorial: clarify nbdev_install and nbdev_preview execution order

### ISSUE THREAD

**Issue by taivop** [fastai/nbdev#785]
I was setting up a fresh project based on the [tutorial](https://nbdev.fast.ai/tutorial.html) and when running `nbdev_preview`, I got a `ModuleNotFoundError` for the module I was trying to develop with nbdev.

After debugging it seems the issue is I was trying to run `nbdev_preview` before I had run `nbdev_install`.

If running `nbdev_install` first is indeed a requirement for starting the preview, it'd be great to mention this in the tutorial. Currently in the tutorial, `nbdev_preview` is mentioned twice before `nbdev_install` so it's really not obvious this should be the case.

**Comment by seeM** [comment]
Thanks @taivop, great point. Would you be open to making a PR with this improvement?

**Comment by ImAKappa** [comment]
I think the tutorial should also point out that each of your notebooks needs to have a cell containing both a h1 heading and some text.

For example, if you have a notebook, say `01_firstnb.ipynb`, with a cell that just contains a heading (`# <Heading>`) like this:

![image](https://user-images.githubusercontent.com/41027138/183318908-15e8642c-6b2f-442c-8f17-2cf790e04a5f.png)

Then you get an error when running `nbdev_preview`:

```bash
Traceback (most recent call last):
  File "/home/kapp/miniconda3/envs/some2/bin/nbdev_filter", line 8, in <module>
    sys.exit(nbdev_filter())
  File "/home/kapp/miniconda3/envs/some2/lib/python3.10/site-packages/fastcore/script.py", line 116, in _f
    return tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/home/kapp/miniconda3/envs/some2/lib/python3.10/site-packages/nbdev/cli.py", line 127, in nbdev_filter
    with redirect_stdout(dn): filt.nb_proc(nb).process()
  File "/home/kapp/miniconda3/envs/some2/lib/python3.10/site-packages/nbdev/process.py", line 128, in process
    self.nb = opt_set(self.nb, proc(self.nb))
  File "/home/kapp/miniconda3/envs/some2/lib/python3.10/site-packages/nbdev/processors.py", line 246, in infer_frontmatter
    _fmdict = merge(nb_fmdict(nb), {'output-file': _exp+'.html'} if _exp else {})
  File "/home/kapp/miniconda3/envs/some2/lib/python3.10/site-packages/nbdev/processors.py", line 217, in nb_fmdict
    title,desc=_re_title.match(cell.source).groups()
AttributeError: 'NoneType' object has no attribute 'groups'
```

However, placing the text in the same cell with the heading resolves the error.
![image](https://user-images.githubusercontent.com/41027138/183319145-676bb2d6-2abf-408a-b0fe-f52c8f0824c1.png)

I think this is because the title regex defined in [processors.ipynb](https://github.com/fastai/nbdev/blob/master/nbs/09_processors.ipynb) expects to find a title heading immediately followed by text:

```python
# taken from nbdev/09_processors.ipynb
_re_title = re.compile(r'^#\s+(.*)[\n\r]+(?:^>\s+(.*))?', flags=re.MULTILINE)
```

Of course, it would be more convenient if this were mentioned in the tutorial (I spent an embarassingly long time resolving the attribute error 😅). A good place to put it would be under the "Preview the Docs" section: [https://nbdev.fast.ai/tutorial.html#preview-the-docs](https://nbdev.fast.ai/tutorial.html#preview-the-docs). Something like, "Make sure your notebook has a cell with a h1 heading (# <Title of Notebook>)" and some text right after it, and not just a h1 heading otherwise the docs won't build."

**Comment by taivop** [comment]
Sure @seeM - didn't wanna embark on a change because it feels like a judgment call how to fix this. There isn't an obvious rearrangement to me; feels more like the whole flow of the tutorial could be more clear.

But specifically for this fix: should we bring `nbdev_install` much earlier, or push `nbdev_preview` later (with potentially a forward reference to that section)?

**Comment by seeM** [comment]
@taivop I see your point! I’ll make it a priority to improve the general flow of the tutorial

**Comment by hamelsmu** [comment]
> I think the tutorial should also point out that each of your notebooks needs to have a cell containing both a h1 heading and some text.

A notebook can have [front matter in a raw cell](https://quarto.org/docs/tools/jupyter-lab.html#yaml-front-matter) or a limited set of front matter in markdown.  

Raw front matter is a [raw cell](https://jupyter-notebook.readthedocs.io/en/stable/notebook.html?highlight=raw%20cell#raw-cells) that looks like this:

```
---
title: A titile
description: My article
toc: true
---
```

Markdown front matter is a [markdown cell](https://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/Working%20With%20Markdown%20Cells.html) that looks like this:

```
# A Title
> My article
- toc: true
```


Raw front matter always takes precedence over markdown and is the recommended way of adding front matter to notebooks. For a list of front matter options, please refer to the [Quarto documentation](https://quarto.org/docs/tools/jupyter-lab.html#yaml-front-matter).

**Comment by seeM** [comment]
@taivop we've reworked the tutorial up to and including [_Preview your docs_](https://nbdev.fast.ai/tutorial.html#preview-your-docs). I'd love to hear your thoughts on the flow now
