### ISSUE TITLE
Write Concepts Page

### ISSUE THREAD

**Issue by hamelsmu** [fastai/nbdev#845]
## Execution Modes
   - nbdev_test
   - nbdev_docs
   - nbdev_filter

Describe:
- What is the purpose of these
- How do they work, conceptually?  How can you debug

## Pandoc
- What is pandoc
- How does it fit in with quarto
- How you can leverage pandoc to customize nbdev

## Writing Source Code
- @patch
- How to test most effectively
- How to debug
- How to use your IDE in addition to notebooks

## Documentation
- How do APIs get documented?
- What are different ways of documenting APIs: numpy, docments, etc.
- How does nbdev render API documentation?

**Comment by seeM** [comment]
Closing, since I think these are now covered:

- "Execution Modes" covered in https://nbdev.fast.ai/explanations/docs.html#concepts
- "Writing Source Code" and "Documentation" covered in the same page and https://nbdev.fast.ai/tutorials/best_practices.html

@hamelsmu we don't cover pandoc much yet, but maybe you can create a new issue for that when you look into it?

**Comment by hamelsmu** [comment]
Sure
