### ISSUE TITLE
Generate submenu item for submodule in sidebar

### ISSUE THREAD

**Issue by benjaminvdb** [fastai/nbdev#85]
Hello all 👋 

I have created several notebooks following a structure like this:

```
10_explore.ipynb
11_explore.first.ipynb
12_explore.second.ipynb
```

each defining a default export, e.g. `# default_exp explore.first` at the top of the notebook.

For readers of my documentation, it would be clear if the submodules (e.g. `explore.first` and `explore.second`) would get their own submenu item in the sidebar. From the [fastai custom sidebar](https://raw.githubusercontent.com/fastai/fastai2/master/docs/sidebar.json), I can see that there is support for this. However, I'm not seeing this being automatically generated. Am I doing something wrong or is automatic generation of submenus not (yet) supported?

**Comment by sgugger** [comment]
It's not yet supported, though it is a very reasonable feature request. It would require a little bit of work but is feasible. I'm putting it on my TODO for when I have time. As a workaround while waiting, use the fastai custom sidebar you mentioned

In the meantime, closing this issue since feature requests should go on the [forum](https://forums.fast.ai/c/fastai-users/nbdev).

**Comment by benjaminvdb** [comment]
@sgugger Sorry! I posted it here out of habit. I didn't know the forum is the place to post feature requests; I was expecting a 'feature request' label here. Perhaps you could include this in the documentation - in case it's not there yet - to save yourself some work?

Thanks for your quick response and keep up the good work 👍
