### ISSUE TITLE
Docs are not generated for exported assignments/vars

### ISSUE THREAD

**Issue by dleen** [fastai/nbdev#865]
A cell like:
```
#| export
x = 1
```
or
```
#| export
x = 1
x
```
Does not result in a doc entry. Is this expected?

Example: https://github.com/dleen/notebook-examples/blob/main/01_var.ipynb

**Comment by dleen** [comment]
Removing `#| export` allows it to appear in the docs.

I tried adding `#| echo: true` and other quarto directives but it doesn't seem to work with export.

**Comment by seeM** [comment]
Does `#| exports` work for this? (`s` for "source")

**Comment by dleen** [comment]
Ah that worked nicely! Hmm is there somewhere that I can find all of the directives? I searched here and found nothing: https://nbdev.fast.ai/export.html

**Comment by seeM** [comment]
I don't think there's a complete reference yet @dleen. Off the top of my head (@hamelsmu @jph00 please double-check):

- `default_exp mod` – `export` to `mod` by default
- `export` – show in docs using `show_doc`; include in module; add to `__all__`; executes in tests
- `exports` (for `s`ource) – like `export` but shows source code in docs instead of `show_doc`
- `exporti` (for `i`nternal) – like `export`, but doesn't show at all in docs and excludes from `__all__`
- no directive – shows in docs as is; executes in tests, or in docs only if it contains `import` or `from * import` (this is also why it's not a good idea to mix imports with code in non-exported cells)
- `hide` – doesn't show at all; executes same as no directive.

I think these are the main nbdev ones. Quarto has its own set too.

@hamelsmu, you were planning on working on some explanatory docs right? I think some variation of above could go a long way.

**Comment by hamelsmu** [comment]
Oh there are lots more directives than that!  I have to collect a list of all of these , it is definitely on the todo list :) Give me a couple of weeks!

**Comment by hamelsmu** [comment]
@dleen I'll go ahead and open an issue and assign it to you.  Let me know if you need any help, happy to review it!
