### ISSUE TITLE
TOC generation breakage

### ISSUE THREAD

**Issue by benjaminvdb** [fastai/nbdev#92]
Hi,

When I put text directly after the notebook title cell, the table of contents is not generated correctly. I've attached a screenshot of the notebook and the resulting documentation page.

- The methods are correctly shown in the TOC, but the headings are not. Instead, they are printed just after the TOC with bullet points.
- The problematic text is not shown in the generated documentation.
- When I insert a new heading right after the title, the TOC is correctly generated.

## Problematic notebook
<img width="216" alt="Screenshot 2020-02-14 at 17 01 43" src="https://user-images.githubusercontent.com/8875786/74546999-b1a8e980-4f4b-11ea-9469-99ed34865503.png">

## Generated documentation
<img width="297" alt="Screenshot 2020-02-14 at 16 58 18" src="https://user-images.githubusercontent.com/8875786/74547004-b4a3da00-4f4b-11ea-8334-90e85a46e8ed.png">

**Comment by sgugger** [comment]
The toc is correctly generated. I think the issue is on jekyll here, which requires to have one header two before header three or four.

You can give a higher header to your calls to `show_doc` with the argument `title_level` (default is 4 for auto-inserted cells, but if you write it yourself, you can specify the one you want) but other than that, there is nothing to be done apart making sure it headers level go increasing.

**Comment by benjaminvdb** [comment]
@sgugger Thanks for the reply. It's not a big issue. I just wanted to be a good citizen and report the problems I'm having with this library. However, it has been a breeze working with `nbdev` and the issues are only minor.

Perhaps a mention of this Jekyll issue can be made in the documentation?

**Comment by sgugger** [comment]
Sure, any PR to add details about this would be most welcome!

**Comment by benjaminvdb** [comment]
Alright, I'll see if I can make some additions. Cheers!
