### ISSUE TITLE
`show_doc` includes parsed sections from numpy docstrings

### ISSUE THREAD

**Issue by rxavier** [fastai/nbdev#964]
Hi! I'm trying to port an existing codebase to nbdev and running into trouble with docstrings. 

I'm not sure if I'm not following numpy style docstrings  as strictly as I should and tripping over the parser in the process, or whether this is a legitimate bug, so here's a minimal example

I've included a method documented with docments which of course renders nicely.

```
#| export

class Test:
    """A class for testing
    
    Second line.
    
    Parameters
    ----------
    x
        First param
    y
        Second param in which I have added a /
        line break due to length
        
    Attributes
    ----------
    comb
        String combination of `x` and `y`
    """
    def __init__(self, x: str, y: Optional[int] = None):
        self.x = x
        self.y = y
        self.comb = x + str(y)
        
    def print(self,
              end: str = "-", # Line ending
              ) -> None: # No need to return anything, just print
        """Print attrs
        
        Print attrs 2
        """
        print(self.x, self.y, end=end)
```

1. A warning is printed in the rendered docs due to the `Attributes` section (`/Users/rafxavier/Envs/poniard/lib/python3.8/site-packages/fastcore/docscrape.py:225: UserWarning: Unknown section Attributes
  else: warn(msg)`). This is probably because [fastcore/docscrape](https://github.com/fastai/fastcore/blob/79469cd899d4fb51007bb2cc6a7a71e05edbafd6/fastcore/docscrape.py#L97) does not support it. Is this intentional? What about other standard numpy sections like `Raises`? The idea is to document these in notebook markdown?
2. Types are correctly pulled from the signature and descriptions from the docstings, and everything is rendered nicely in a table. However, a `Parameters` section with weird formatting is also included.
<img width="801" alt="image" src="https://user-images.githubusercontent.com/12989861/187760395-f3ec51ff-0227-4332-bd04-c9f9a0822059.png">
3. If the parameter description has a line break, it's not rendered correctly in the table
<img width="783" alt="image" src="https://user-images.githubusercontent.com/12989861/187761416-53bc8b23-5d50-4757-97de-5b0ff9e5b787.png">

**Comment by seeM** [comment]
Thanks for the clear issue write-up! :) #969 fixes (1) redundant sections in numpy docstrings and (2) newlines in the parameters table. Here's what it looks like with the fix:

<img width="780" alt="image" src="https://user-images.githubusercontent.com/559360/187841591-bfe25991-2b3a-4510-a4f9-6c62d29aaf29.png">

> Is this intentional? What about other standard numpy sections like Raises? The idea is to document these in notebook markdown?

Our preferred approach is to document almost everything in separate code and markdown cells below the definition of your function/class. This gives the most flexibility, since you can write and execute arbitrary code, and you have access to any valid markdown (and even HTML/CSS/JS). Some of these examples can function as unit tests. For example, here's how I would document your example class:

<img width="907" alt="image" src="https://user-images.githubusercontent.com/559360/187842610-a172deac-3cf8-4105-ab25-67a0472970bc.png">

...and here's how it gets rendered as documentation:

<img width="770" alt="image" src="https://user-images.githubusercontent.com/559360/187842690-a6f035d2-07aa-4d48-935c-19fefc27f1e3.png">

For documenting "raises", I would consider using `fastcore.test.test_fail` to demonstrate failure cases.

**Comment by rxavier** [comment]
Thank you for the quick fix @seeM!

I have to get used to nbdev's more flexible approach to documentation. In many ways I think it's superior but it takes a change of perspective.

**Comment by jph00** [comment]
@seeM should we add `attributes` etc to docscrape before we close this? I'll reopen this for now - feel free to close if you think it's not an issue.

**Comment by rxavier** [comment]
@jph00 

> @seeM should we add `attributes` etc to docscrape before we close this? I'll reopen this for now - feel free to close if you think it's not an issue.

If it's okay, I'll add my 2c: covering the main numpy sections would reduce a lot of the friction for existing libraries to migrate to nbdev. Contributors could then slowly adopt nbdev's way of documenting, but with a working migration in place.

**Comment by jph00** [comment]
That's a good point @rxavier.

OTOH, the reason I didn't include support for those sections in the 1st place was because using them in nbdev is not really best practice use of nbdev.

Perhaps what we really need is to support them, but also print out a message mentioning that's there's better ways to do it in nbdev, with a link to a best practices authoring guide?

**Comment by seeM** [comment]
Good questions. I was initially hesitant because it meant supporting [15 possible sections](https://numpydoc.readthedocs.io/en/latest/format.html#sections) each of which is also rendered in slightly different ways, which seemed like a lot to maintain, especially when putting everything in the docstring is the opposite of the recommended approach.

I do see the value in allowing people to slowly migrate over, though, so I do think it's worth investigating.

There are also open questions for nbdev-style docs, like whether we could/should have a parameter table for object attributes, raises, and "see also" blocks ([this page from numpy docs](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html#numpy.ndarray) demonstrates a few of these). These could also be documented in a best practices authoring guide.

**Comment by jph00** [comment]
Created an issue to track adding an appropriate warning - I think that might be the best next step
#981
