### ISSUE TITLE
add easy to spin up environment for development

### ISSUE THREAD

**Issue by kevinbird15** [fastai/nbdev#996]
I wanted to see if there would be interest in either creating a docker-compose file that would quickly spin up a development environment or a devcontainer that would make it easier to get into a clean install of the repo for new development.

Would this be something that the core team would want?  I enjoy using docker-compose to develop because it makes it easy to clone the repo in any environment and start working quickly, but I'm not sure if that's how most people do dev work.

**Comment by jph00** [comment]
Personally I just use conda/mamba to do that -- `mamba create -n nbdev -c fastai nbdev jupyter` followed by `conda activate nbdev` should suffice IIRC. But I'm not a big docker user in general.

@seeM @hamelsmu what do you think?

**Comment by seeM** [comment]
There was one time I couldn't figure out an ubuntu-specific bug from our CI (since I'm on mac) and setup a quick & hacky Dockerfile to debug it, otherwise I wouldn't personally use this. Maybe that will change if/when we think about running cloud dev environments

For now though, maybe this could be maintained in a separate repo and the nbdev docs could link out to it?

**Comment by jph00** [comment]
@kevinbird15 I'll close this since it's not really our recommended approach for now, but it might be cool to publish a gist, repo, or blog post documenting it for folks who would find it helpful?

**Comment by hamelsmu** [comment]
I've been using modal 

See https://github.com/hamelsmu/try_modal, and the python file at the root of the repo.  It's one of my favorite things now
